### ISSUE TITLE
Difference between derive and proxyWithComputed?

### ISSUE THREAD

**Issue by jeffjose** [wobsoriano/sveltio#1]
It sounds like both `derive` and `proxyWithComputed` can be used to create new attributes that respond to changes in the original state, but sounds like there's a subtle difference?

**Comment by wobsoriano** [comment]
`derive` can create a new proxy, whereas `proxyWithComputed` can only attach properties to the self-proxy.

Per Daishi, use `derive` first, and only reach out `proxyWithComputed` if something doesn't work as expected.
