### ISSUE TITLE
Module '"sveltio/utils"' has no exported member 'derive'.ts(2305)

### ISSUE THREAD

**Issue by KiddoV** [wobsoriano/sveltio#4]
This is weird...

![err](https://github.com/user-attachments/assets/3bbb5bc1-284a-48a8-bba9-32181ce803ed)

Am I missing anything?

**Comment by wobsoriano** [comment]
Looks like they removed a bunch of utils from that package and can be installed separately.

https://valtio.dev/docs/api/utils/derive

**Comment by KiddoV** [comment]
@wobsoriano should you update your lib as well?

**Comment by KiddoV** [comment]
@wobsoriano thank you!

**Comment by wobsoriano** [comment]
Ill probably try and add support for svelte runes today
